### PR TITLE
Promise reject exception slicing

### PR DESCRIPTION
**Pull request by brainysmith**
Fixed a bug described in question: http://stackoverflow.com/questions/33647949/firebreath-promise-reject-slicing-exception.

### CODE REVIEW

**Comment by taxilian** [comment]
Sorry I haven't fully reviewed this yet; it's kinda a critical thing to get right but it's doing a few things I haven't seen before and I just haven't had time to fully look through it

**Comment by taxilian** [comment]
As a minor point of feedback, the line spacing changes which are incidental to the PR make it much harder to review as well

**Comment by brainysmith** [comment]
Thanks for your feedback. Sorry for the line spacing changes, I can fix them now or wait you give the feedback about the implementation itself. What the way is better?

**Comment by taxilian** [comment]
Fixing them would help =] I'll try to review them either way in the next day or so.  Feel free to bug me every few days or so until I finish if I don't get it done soon enough =] this is important, I just have a ton of stuff going on right now

**Comment by taxilian** [comment]
Actually, I just went through it with some docs and it made a lot more sense to me this time.  I've never even heard of std::current_exception() or std::rethrow_exception; those are absolutely perfect for this problem.  *awesome*! Thank's for putting this together; if you don't mind normalizing the line spaces (4 spaces, no tabs) I'll merge it once that's done.

**Comment by brainysmith** [comment]
Good! I will fix it tomorrow.

**Comment by brainysmith** [comment]
I have fixed the line spaces.

**Comment by taxilian** [comment]
Awesome, thanks! Now we just need some examples and getting started instructions for the FB 2.0 branch... ;-)

**Pull request merged**
