### PR TITLE
Add VS 2015 RTM support

### PR DESCRIPTION
**Pull request by AndyTather**
Add VS 2015 RTM support, code changes from master.

Not sure about the boost link in this PR, sourcetree made this link

### CODE REVIEW

**Comment by taxilian** [comment]
Two questions:

1) What changes did you make to boost? They aren't available in the firebreath-boost repo, so this is not merge-able as it currently is.

2) Why did you remove the messages from the std::bad_cast exceptions?

**Comment by AndyTather** [comment]
1). Changes made to the sub-project didn't seem to come through via sourcetree.  Might need your assistance on this one.  Have made a PR for the boost project: https://github.com/firebreath/firebreath-boost/pull/4

2). Needed this changeset from master to compile under vs2015.
https://github.com/firebreath/FireBreath/commit/938dcf504a602ad3427eb2b0e3ad1eea2e5fed5e

**Comment by taxilian** [comment]
According to microsoft's documentation, bad_cast can take a const char*; thus there should be no need for that changeset to compile under vs2015:

https://msdn.microsoft.com/en-us/library/82f1eehz.aspx

Could you try again? Perhaps it's just missing an include somewhere.

**Comment by taxilian** [comment]
Also, I accepted your pull request on the boost library; if you could add to this the correct hash from the FireBreath/firebreath-boost repo that would be helpful.

**Comment by AndyTather** [comment]
Thanks.  Updated boost to the correct hash.

Looking at the bad_cast issue.

**Comment by AndyTather** [comment]
The bad_cast with parameter does present a problem.

In VS2015 the preprocessor variable _HAS_EXCEPTIONS defaults 1, which in turn changes the prototype of:
bad_cast(const char *_Message = "bad cast")
into this:
static bad_cast __construct_from_string_literal(char const* const _Message)

Naturally overriding the _HAS_EXCEPTIONS to 0 uses the first prototype but there is a reported issue to VS2015 team about other errors which fail.

So in VS2015 we can use:
throw std::bad_cast::__construct_from_string_literal("This is not a valid object");

but this won't compile in VS2013.

**Comment by taxilian** [comment]
That is very strange.  Why don't you just change the exception type to something else -- std::runtime_error for example.  I'd rather not lose the error message, since that will actually make it out to the page in most cases.

Any exception that extends std::runtime_error should be fine, choose the one you think works best.

**Comment by AndyTather** [comment]
Gone for the base class of bad_cast which does support a suitable constructor for the message, on all compilers.

Definitely a strange one!

**Comment by AndyTather** [comment]
Git 'Squished' commits into one

**Comment by taxilian** [comment]
Hmm; I'll have to check, I don't remember if std::exception is handled or not, it may need to be something that extends runtime_error. I'll look and get back to you.

**Comment by AndyTather** [comment]
I think in the MS world both bad_cast and runtime_error derive from std::exception.

According to a this post http://stackoverflow.com/questions/1569726/difference-stdruntime-error-vs-stdexception the std::exception shouldn't take any parameters (C++ std), so I'll change them to at least runtime_error.

**Pull request closed without merging**
